#!/usr/bin/env node

/**
 * Embed Configuration Script
 * 
 * Generates index.html from index.html.template by embedding the configuration
 * from public/config.json. This prevents environment-specific data from being
 * committed to source control.
 * 
 * The template contains a placeholder: window.__EMBEDDED_CONFIG__ = {};
 * This script replaces it with the actual configuration values.
 * 
 * Usage: node scripts/embed-config.js
 */

const fs = require('fs');
const path = require('path');

const CONFIG_PATH = path.join(__dirname, '..', 'public', 'config.json');
const TEMPLATE_PATH = path.join(__dirname, '..', 'index.html.template');
const OUTPUT_PATH = path.join(__dirname, '..', 'index.html');

console.log('🔐 Generating index.html from template with embedded configuration...');

// Read config.json
if (!fs.existsSync(CONFIG_PATH)) {
  console.error('❌ Error: public/config.json not found. Run "npm run generate-config" first.');
  process.exit(1);
}

// Read template
if (!fs.existsSync(TEMPLATE_PATH)) {
  console.error('❌ Error: index.html.template not found.');
  process.exit(1);
}

const config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
console.log('✅ Loaded configuration from public/config.json');

let html = fs.readFileSync(TEMPLATE_PATH, 'utf8');

// Replace the placeholder with actual configuration
const placeholderRegex = /window\.__EMBEDDED_CONFIG__\s*=\s*\{\}[^;]*;/;
const newConfigString = `window.__EMBEDDED_CONFIG__ = ${JSON.stringify(config, null, 2)}; // generated by scripts/embed-config.js via npm run build:production`;

if (!placeholderRegex.test(html)) {
  console.error('❌ Error: Could not find __EMBEDDED_CONFIG__ placeholder in index.html.template');
  process.exit(1);
}

html = html.replace(placeholderRegex, newConfigString);

// Write generated index.html
fs.writeFileSync(OUTPUT_PATH, html, 'utf8');

console.log('✅ Generated index.html from template');
console.log('📝 Configuration embedded for production deployment');
console.log(`   Region: ${config.region}`);
console.log(`   Instance: ${config.instanceAlias || config.instanceId}`);
